version: '3.8'
services:
  echopay:
    image: kbdemiranda/echopay:latest
    container_name: echopay
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - echopay-network

  processor:
    image: kbdemiranda/echopay-processor:latest
    container_name: processor
    ports:
      - "8081:8081"
    environment:
      ECHO_PAY_URL: http://echopay:8080/api/transactions/
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ECHOPAY_SERVICE_URL: http://echopay:8080/api/transactions/
    depends_on:
      - kafka
      - echopay
    networks:
      - echopay-network

  postgres:
    image: kbdemiranda/postgres:bullseye
    container_name: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - echopay-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper
    networks:
      - echopay-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/var/lib/kafka
    networks:
      - echopay-network

volumes:
  postgres-data:
  zookeeper-data:
  kafka-data:

networks:
  echopay-network:
    driver: bridge
